require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "Rakefile"
    - "tmp/**/*"
    - ".git/**/*"
  TargetRubyVersion: 2.5
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 1000
Metrics/MethodLength:
  Max: 250
Metrics/ClassLength:
  Max: 1000
Metrics/AbcSize:
  Max: 250
Metrics/BlockLength:
  Max: 1500
Metrics/CyclomaticComplexity:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 50
Style/ClassAndModuleChildren:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/AndOr:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
RSpec/ContextWording:
  Enabled: false
